[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"



[project]
name = "Viz"
version = "0.0.1"
dependencies = [
    "mujoco",
    "matplotlib",
    "setuptools",
    "numpy==1.26.4"
]
